# Generated by Django 4.2.5 on 2023-10-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus_name', models.CharField(max_length=128)),
                ('en_name', models.CharField(max_length=128)),
                ('alt_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('count_view', models.IntegerField()),
                ('count_like', models.IntegerField()),
                ('tags', models.ManyToManyField(related_name='titles', to='api.tag')),
            ],
            options={
                'ordering': ['count_view'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='api.title')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField()),
                ('index', models.IntegerField()),
                ('content', models.TextField()),
                ('volume', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.volume')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
