# Generated by Django 4.2.5 on 2023-10-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='index',
        ),
        migrations.AlterField(
            model_name='title',
            name='alt_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='title',
            name='count_like',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='title',
            name='count_view',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='en_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
