# Generated by Django 4.2.5 on 2023-10-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231003_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['id']},
        ),
    ]
