# Generated by Django 4.2.5 on 2023-10-03 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_remove_title_count_like_remove_title_count_view_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['id']},
        ),
    ]
